# Generated by Django 4.2.3 on 2023-07-16 04:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user_type",
            field=models.CharField(
                default="guest", max_length=30, verbose_name="User type"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=[], size=None
            ),
        ),
    ]
