# Generated by Django 4.2.3 on 2023-08-10 01:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_user_type_alter_account_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=account.models.upload_location
            ),
        ),
    ]
