# Generated by Django 4.2.3 on 2023-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bio",
            field=models.CharField(
                blank=True,
                default="I m a bachelor graduate from Islington college, Nepal acheiving 71 percentage overall and currently working as a backend developer using Ruby on Rails.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="languages",
            field=models.CharField(default="English", max_length=50),
        ),
    ]
