# Generated by Django 4.2.3 on 2023-08-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_account_bio_account_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="sign_in_mode",
            field=models.CharField(blank=True, default="normal", max_length=30),
        ),
    ]
