# Generated by Django 4.2.3 on 2023-08-16 05:41

import account.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_account_sign_in_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="profile_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=40,
                scale=None,
                size=[1024, 768],
                upload_to=account.models.upload_location,
            ),
        ),
    ]
