# Generated by Django 4.2.3 on 2023-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_account_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="languages",
            field=models.CharField(
                blank=True, default="English", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_type",
            field=models.CharField(
                blank=True, default="guest", max_length=30, verbose_name="User type"
            ),
        ),
    ]
