# Generated by Django 4.2.3 on 2023-08-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_account_bio_alter_account_languages_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="bio",),
        migrations.RemoveField(model_name="account", name="country",),
        migrations.RemoveField(model_name="account", name="languages",),
        migrations.RemoveField(model_name="account", name="skills",),
    ]
