# Generated by Django 4.2.3 on 2023-08-31 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_remove_account_bio_remove_account_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freelancerdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=3)),
                ("state", models.CharField(max_length=20)),
                ("zip", models.IntegerField()),
                ("street_address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=20)),
                ("zip", models.IntegerField()),
                ("street_address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
