# Generated by Django 4.2.3 on 2023-08-31 08:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_resume_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("currently_working", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "resume",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_experience",
                        to="account.resume",
                    ),
                ),
            ],
        ),
    ]
