# Generated by Django 4.2.3 on 2023-09-04 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="freelancer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_resume",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
