# Generated by Django 4.2.3 on 2023-09-08 04:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_alter_resume_freelancer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=200), size=8
                ),
                size=1,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=200), size=8
                ),
                size=1,
            ),
        ),
    ]
