# Generated by Django 4.2.3 on 2023-09-11 07:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_resume_languages_alter_resume_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="country",
            field=django_countries.fields.CountryField(default="AU", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resume",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), size=8
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200), size=8
            ),
        ),
    ]
