# Generated by Django 4.2.3 on 2023-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_account_country_alter_resume_languages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=200)),
                (
                    "joined_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="Last login"),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
