# Generated by Django 4.2.3 on 2023-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_admindetails"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admindetails", old_name="name", new_name="first_name",
        ),
        migrations.AddField(
            model_name="admindetails",
            name="last_name",
            field=models.CharField(default="admin", max_length=50),
            preserve_default=False,
        ),
    ]
