# Generated by Django 4.2.3 on 2023-09-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_rename_name_admindetails_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admindetails",
            name="status",
            field=models.CharField(default="waiting", max_length=200),
        ),
    ]
