# Generated by Django 4.2.3 on 2023-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_admindetails_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="admindetails",
            name="token",
            field=models.CharField(default="token", max_length=200),
        ),
    ]
