# Generated by Django 4.2.3 on 2023-09-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_admindetails_token"),
    ]

    operations = [
        migrations.RemoveField(model_name="admindetails", name="password",),
        migrations.AlterField(
            model_name="account",
            name="title",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Title"
            ),
        ),
    ]
