# Generated by Django 4.2.3 on 2023-08-08 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.IntegerField()),
                ("requested_rate", models.IntegerField()),
                ("requested_hour", models.DecimalField(decimal_places=2, max_digits=5)),
                ("requested_completion_time", models.CharField(max_length=50)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="freelancer id",
                    ),
                ),
            ],
        ),
    ]
