# Generated by Django 4.2.3 on 2023-08-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_jobbid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobbid", old_name="client", new_name="client_id",
        ),
    ]
