# Generated by Django 4.2.3 on 2023-08-08 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0003_rename_client_jobbid_client_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobbid", name="client_id",),
        migrations.AddField(
            model_name="jobbid",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobbid",
            name="freelancer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
