# Generated by Django 4.2.3 on 2023-08-10 02:26

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_remove_jobbid_client_id_jobbid_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=job.models.upload_location
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="task_type",
            field=models.CharField(default="IT", max_length=50),
        ),
    ]
