# Generated by Django 4.2.3 on 2023-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_job_image_job_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="unique_field",
            field=models.CharField(default="dsa", max_length=50),
        ),
    ]
