# Generated by Django 4.2.3 on 2023-08-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_job_unique_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="unique_field",),
    ]
