# Generated by Django 4.2.3 on 2023-08-10 09:08

from django.db import migrations
import django_resized.forms
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_alter_job_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=40,
                scale=None,
                size=[1024, 768],
                upload_to=job.models.upload_location,
            ),
        ),
    ]
