# Generated by Django 4.2.3 on 2023-08-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_agreedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreedjob",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="job.job",
            ),
        ),
    ]
