# Generated by Django 4.2.3 on 2023-08-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0013_rejectionreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_status",
            field=models.CharField(default="not assigned", max_length=50),
        ),
    ]
