# Generated by Django 4.2.3 on 2023-08-28 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0014_job_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionreason",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rejectionreason",
            name="freelancer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
