# Generated by Django 4.2.3 on 2023-08-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0015_rejectionreason_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobbid",
            name="status",
            field=models.CharField(default="not reviewed", max_length=50),
        ),
    ]
