# Generated by Django 4.2.3 on 2023-08-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0016_jobbid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
