# Generated by Django 4.2.3 on 2023-08-31 02:07

from django.db import migrations, models
import django_resized.forms
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0017_job_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=30)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        null=True,
                        quality=40,
                        scale=None,
                        size=[1024, 768],
                        upload_to=job.models.category_upload_location,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
