# Generated by Django 4.2.3 on 2023-08-31 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0018_jobcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategories",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2023, 8, 31, 2, 20, 28, 704120, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
