# Generated by Django 4.2.3 on 2023-09-11 10:25

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0019_jobcategories_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSubCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category_name", models.CharField(max_length=50)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="JPEG",
                        keep_meta=True,
                        null=True,
                        quality=40,
                        scale=None,
                        size=[1024, 768],
                        upload_to=job.models.category_upload_location,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="jobcategories",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
