# Generated by Django 4.2.3 on 2023-09-11 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0020_jobsubcategories_jobcategories_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsubcategories",
            name="job_categories",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_categories",
                to="job.jobcategories",
            ),
        ),
    ]
