# Generated by Django 4.2.3 on 2023-09-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0022_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.jobsubcategories",
                verbose_name="job_sub_category",
            ),
            preserve_default=False,
        ),
    ]
