# Generated by Django 4.2.3 on 2023-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0023_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="freelancer_experience",
            field=models.CharField(default="experienced", max_length=50),
            preserve_default=False,
        ),
    ]
