# Generated by Django 4.2.3 on 2023-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0024_job_freelancer_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job", name="completion_time", field=models.DateField(),
        ),
    ]
