# Generated by Django 4.2.3 on 2023-09-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0025_alter_job_completion_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="hour",),
        migrations.AddField(
            model_name="job",
            name="price_per",
            field=models.CharField(default="per_project", max_length=200),
            preserve_default=False,
        ),
    ]
