# Generated by Django 4.2.3 on 2023-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0028_jobapplies"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplies",
            name="status",
            field=models.CharField(default="requested", max_length=50),
        ),
    ]
