# Generated by Django 4.2.3 on 2023-09-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0029_jobapplies_status"),
    ]

    operations = [
        migrations.DeleteModel(name="JobBid",),
    ]
