# Generated by Django 4.2.3 on 2023-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0032_remove_agreedjob_agreed_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreedjob",
            name="agreed_price_per",
            field=models.CharField(default="per_project", max_length=50),
            preserve_default=False,
        ),
    ]
