# Generated by Django 4.2.3 on 2023-09-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0033_agreedjob_agreed_price_per"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionreason",
            name="reject_option",
            field=models.CharField(default="price_too_low", max_length=500),
            preserve_default=False,
        ),
    ]
