# Generated by Django 4.2.3 on 2023-09-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0037_userpayment"),
    ]

    operations = [
        migrations.RemoveField(model_name="userpayment", name="app_user",),
    ]
