# Generated by Django 4.2.3 on 2023-09-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0038_remove_userpayment_app_user"),
    ]

    operations = [
        migrations.DeleteModel(name="UserPayment",),
    ]
