# Generated by Django 4.2.3 on 2023-09-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0039_delete_userpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bool", models.BooleanField(default=False)),
                ("stripe_checkout_id", models.CharField(max_length=500)),
                (
                    "job_agreed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.agreedjob"
                    ),
                ),
            ],
        ),
    ]
