# Generated by Django 4.2.3 on 2023-09-27 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0040_userpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
